import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "./_components/footer/footer";

const firaSans = localFont({
  src: "./fonts/FiraCode-Medium.ttf",
  variable: "--font-fira-sans",
  weight: "100 900",
});
const firaMono = localFont({
  src: "./fonts/FiraCode-Medium.ttf",
  variable: "--font-fira-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${firaSans.variable} ${firaMono.variable} antialiased flex  flex-col justify-between`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
